# Generated by Django 3.0.4 on 2020-08-13 02:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients', '0017_ingredient_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('serving', models.DecimalField(blank=True, decimal_places=1, help_text='Optional grams per serving. WARNING Nutrients are still entered per-KG.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('introduction', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='ingredients.ItemTag')),
            ],
        ),
    ]
