# Generated by Django 3.0.4 on 2020-08-13 04:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0018_item_itemtag'),
        ('recipes', '0024_recipe_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, help_text='Amount, either grams or servings depending on the unit', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('g', 'grams'), ('srv', 'servings')], default='g', max_length=3)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_of', to='ingredients.Item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='items',
            field=models.ManyToManyField(through='recipes.RecipeItem', to='ingredients.Item'),
        ),
    ]
